# Generated by Django 3.2.6 on 2021-09-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigIntegerField(primary_key=True)),
                ('repo_name', models.TextField()),
                ('repo_full_name', models.TextField()),
                ('pull_request_number', models.IntegerField()),
                ('pull_request_url', models.TextField()),
                ('pull_request_title', models.TextField()),
                ('pull_request_created_at', models.TextField()),
                ('pull_request_updated_at', models.TextField()),
            ],
        ),
    ]
