# Generated by Django 3.2.6 on 2021-09-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('repo_name', models.TextField()),
                ('repo_full_name', models.TextField()),
                ('repo_clone_url', models.TextField()),
                ('repo_git_url', models.TextField()),
                ('repo_html_url', models.TextField()),
            ],
        ),
    ]
