# Generated by Django 3.2.6 on 2021-09-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_repo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('repo_name', models.TextField()),
                ('repo_full_name', models.TextField()),
                ('issue_number', models.IntegerField()),
                ('issue_url', models.TextField()),
                ('issue_title', models.TextField()),
                ('issue_created_at', models.TextField()),
                ('issue_updated_at', models.TextField()),
            ],
        ),
    ]
