# Generated by Django 3.2.7 on 2022-12-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_closed_at',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_state',
            field=models.TextField(default='open'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='pull_request_closed_at',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='pull_request_state',
            field=models.TextField(default='open'),
            preserve_default=False,
        ),
    ]
