# Generated by Django 3.2.7 on 2022-12-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0004_auto_20221205_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='pull_request_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='pull_request_created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='pull_request_updated_at',
            field=models.DateTimeField(),
        ),
    ]
