# Generated by Django 3.2.7 on 2022-07-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('library', models.CharField(max_length=50)),
                ('lines_of_code', models.IntegerField()),
                ('lines_of_tests', models.IntegerField()),
                ('commits_one_month', models.IntegerField()),
                ('commits_one_year', models.IntegerField()),
                ('dependency_level', models.IntegerField()),
                ('dependency_weight', models.IntegerField()),
                ('issues', models.IntegerField()),
                ('pull_requests', models.IntegerField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'stats',
            },
        ),
    ]
