# Generated by Django 3.2.7 on 2022-12-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boostlibrarystats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='issues_all',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='pull_requests_all',
            field=models.IntegerField(default=0),
        ),
    ]
